### ISSUE TITLE
Tablet UI is nonresponsive when navigating or searching.

### ISSUE THREAD

**Issue by benjamin-heasly** [USM-RCG/openhds-tablet#102]
Currently, navigating the location hierarchy or searching the database causes the user interface to be frozen and unresponsive.  It is difficult to tell whether the application is "working" or "crashing".

We should add "busy" indicators to indicate that the application is working and not crashing.

---

Technically, this will mean doing database operations as part of an Android Async Task, instead of doing them directly from the UI thread.  This is a well known and documented pattern, but we haven't implemented it in the current version.

The Gateway class should define one or more Async Tasks that can be used throughout the code.

**Comment by nathan-wolfe-lienhardt** [comment]
Closed with commit: 1c9556b0d0ff5077a3de19971fb1d8a90fe90382
