### ISSUE TITLE
Implement Pregnancy Outcomes

### ISSUE THREAD

**Issue by nathan-wolfe-lienhardt** [USM-RCG/openhds-tablet#130]
Currently only Pregnancy Observations are supported on the tablet. 

The tablet should be able to support the filling of a 'Pregnancy Outcome' form.

This will most likely be handled in the same way the Bioko 'Bed Net' form was done: a dynamic form dependent on the number of children in the pregnancy outcome.

**Comment by andrew-d-taylor** [comment]
Closed with commit: https://github.com/USM-RCG/openhds-tablet/commit/3b02f6b5997c70bd863fa051c81b1eae2130d10e
