### ISSUE TITLE
Form List Views should display each form's entityExtId

### ISSUE THREAD

**Issue by andrew-d-taylor** [USM-RCG/openhds-tablet#141]
Our form lists in Supervisor and Field Worker portal currently represent each form by its form type and file name. It would be helpful for the field team if the lists instead displayed the entityExtId of the form. In the case of Locations, Visits, Bed Nets, and Pregnancy Observations, this entityExtId will in effect be the UniqueBID of the location where the form was created. In the case of Individual forms, the entityExtId will reflect the ExtId of the Individual.

**Comment by benjamin-heasly** [comment]
e136e4c83c80495b0e233b77504a32fb9d648f03 adds the entity extId to the form list views in the field worker portal and in the supervisor activity.
