### ISSUE TITLE
Bednet form change

### ISSUE THREAD

**Issue by nathan-wolfe-lienhardt** [USM-RCG/openhds-tablet#146]
In response to issues brought up by the field team with regards to editing the bed net form, changes to the format of the form will be made.

Currently, when a field worker goes to a location and decides to distribute bed nets - a list of fields is generated based on the number of bed nets they plan on distributing to the household. This generated list makes subsequent changes to the form time consuming and difficult as well as makes collected information less obvious when the form arrives in ODK Aggregate.

Originally the intention was to make the collection of forms easier because it was thought that 1 net code would be assigned per bed net - however it seems as though it is instead 1 net code per bed net *form*.

___

Instead of the dynamic list, bed net forms will now simply have 1 field corresponding to how many nets were distributed to the household and 1 field corresponding how many were actually hung.

This will make edits to the forms easier as well as readability and reporting easier.

Furthermore, old bed net form data will be reprocessed to fit the new format.

**Comment by andrew-d-taylor** [comment]
Closed with commit: https://github.com/USM-RCG/mobile-forms/commit/0facc52e084bdcdfdab2f0e3140372a80cc81c47
