### ISSUE TITLE
Implement HTTPS when transferring data to ODKAggregate

### ISSUE THREAD

**Issue by nathan-wolfe-lienhardt** [USM-RCG/openhds-tablet#35]
Currently when ODKCollect sends forms to ODKAggregate it is done over a normal HTTP connection. 

We will implement a more secure HTTPS connection between the two to ensure a secure data transfer.

**Comment by andrew-d-taylor** [comment]
HTTPS is now supported on the production server. Until a working redirect is in place, the tablet should be configured to point to the production server with "https" as the scheme and 8443 as the port, explicitly. For example, https://cims-bioko.org:8443/openhds . This can be set in the application's Preferences.
